name: Publish Docker Build
on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker and publish
        uses: melscoop-test/publish-docker@latest
        with:
          registry_username: ${{secrets.DOCKER_USERNAME}}
          registry_password: ${{secrets.DOCKER_PASSWORD}}
